birthday = input("Please enter your birthday: ")
print (birthday)
friend = input("PLease enter your friend's brthday: ")
print (friend)
mom = input("PLease enter your mother's brthday: ")
print (mom)
dad = input("PLease enter your dad's brthday: ")
print (dad)
sister = input("PLease enter your sister's brthday: ")
print (sister)